config/routes.rb
Rails.application.routes.draw do
  root 'users#show'

  post 'event_create', to: 'events#create'

  resources :events
  resources :users, only: %i[new create show]
  resources :events, except: %i[destroy update edit] do
    member do
      get 'attend'
    end
  end
  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :event_attendances, foreign_key: 'attended_events'
  has_many :attendees, through: :event_attendances

  scope :upcoming_events, -> { where('date > ?', Time.now) }
  scope :past_events, -> { where('date < ?', Time.now) }

  validates :title, :date, :location, :description, presence: true
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id'
  has_many :event_attendances, foreign_key: 'attendee_id'
  has_many :attended_events, through: 'event_attendances'
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user != nil
  end
end

app/controllers/events_controller.rb
# Event controller class
class EventsController < ApplicationController
  before_action :logged_in?, except: [:index]
  def new
    @created_event = current_user.created_events.build
  end

  def index
    @created_events = Event.all
    @past_events = Event.past_events
    @upcoming_events = Event.upcoming_events
  end

  def show
    @created_event = Event.find(params[:id])
  end

  def create
    @created_event = current_user.created_events.build(event_params)
    # @created_event.attendees << current_user
    if @created_event.save
      flash[:notice] = "#{@created_event.title} was successfully created."
      redirect_to root_path
    else
      flash[:alert] = 'You need to create a valid event'
      render :new
    end
  end

  def attend
    @created_event = Event.find(params[:id])
    @created_event.attendees << current_user
    flash[:notice] = "You are attending :#{@created_event.title}"
    redirect_to current_user
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :location, :creator_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(name: params[:name])
    if user.present?
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to root_path
    else
      flash[:alert] = 'Invalid credential'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "#{@user.name} is created successfully"
      redirect_to root_path
    else
      render :new
    end
  end

  # main controller
  def show
    @user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors(item)
    output = ''
    if item.errors.any?
      item.errors.full_messages.each do |message|
        output << "<div class='notification is-danger'> #{message} </div>"
      end
    end
    output.html_safe
  end

  def header_display
    output = ''
    output << if logged_in?
                "<h2 class='button is-static is-light'>Welcome  #{current_user.name} </h2>
     #{link_to 'Log Out', logout_path, method: 'delete', class: 'button is-primary'}"
              else
                "#{link_to 'Sign Up', sign_up_path, class: 'button is-primary'}
     #{link_to 'Sign In', sign_in_path, class: 'button is-light'}"
              end
    output.html_safe
  end

  def flash_notice
    output = ''
    if flash[:notice]
      output << "<div class='notification is-primary'>
        #{flash[:notice]}
      </div>"
    end

    if flash[:alert]
      output << "<div class='notification is-danger'>
         #{flash[:alert]}
      </div>"
    end
    output.html_safe
  end
end

app/helpers/events_helper.rb
# rubocop:disable Style/GuardClause:

module EventsHelper
  def show_status(current_user)
    if logged_in?
      if @created_event.creator == current_user
        "<div class='button is-danger ml-2 mb-3'> <span>Hosting  <i class='fa fa-check'></i></span></div>".html_safe
      elsif @created_event.attendees.include?(current_user)
        "<div class='button is-danger ml-2 mb-3'> <span>Attending  <i class='fa fa-check'></i></span></div>".html_safe
      else
        (button_to 'Attend', attend_event_path, method: :get, class: 'button is-info').to_s.html_safe
      end
    end
  end

  def all_events
    output = ''
    @created_events.each do |created_event|
      output << "<h3 class='subtitle'> #{created_event.title} </h3>
      <p>  #{created_event.description} <span> #{created_event.date}</span></p>"
    end
    output.html_safe
  end

  def return_upcoming_events(item)
    output = ''
    if item.upcoming_events.present?
      item.upcoming_events.each do |event|
        output << "<li> <strong> #{link_to event.title, event_path(event)} </strong></li>"
      end
    else
      output << '<p> No upcoming Events </p>'
    end
    output.html_safe
  end

  def return_past_events(item)
    output = ''
    if item.past_events.present?
      item.past_events.each do |event|
        output << "<li> <strong> #{event.title} </strong> </li>"
      end
    else
      output << '<p> No past Events </p>'
    end
    output.html_safe
  end
end
# rubocop:enable Style/GuardClause:

app/helpers/users_helper.rb
module UsersHelper
  def show_user_create(current_user)
    output = ''
    if logged_in?
      output << if current_user.created_events.any?
                  "<p> You have: #{current_user.created_events.count}  events </p>
          #{link_to 'Create Event', new_event_path, class: 'button is-light'}"
                else
                  "<h1>No events </h1>
       #{link_to 'Create Event', new_event_path, class: 'button is-light'} "
                end
    end
    output.html_safe
  end

  def logged(model)
    output = ''
    if logged_in?
      if model.past_events.any?
        output << "<h2 class='subtitle'>Past Events </h2><p> There are #{model.past_events.count}  past events</p>"
        model.past_events.each do |event|
          output << "<ul>
                <li> #{event.title} | #{event.date} | #{event.location}   </li>
            </ul>"
        end
      else
        output << '<p> You have no past events. </p>'
      end

      if model.upcoming_events.any?
        output << "<h2 class='subtitle'>Upcoming  Events </h2>
        <p>There are #{model.upcoming_events.count} upcoming events</p>"
        model.upcoming_events.each do |event|
          output << "<ul>
                <li> #{event.title} | #{event.date} | #{event.location}   </li>
            </ul>"
        end
      else
        output << '<p> You have no upcoming events. </p>'
      end
    else
      Event.all.each do |created_event|
        output << "<h3 class='subtitle'> #{created_event.title} </h3>
        <p> #{created_event.description} <span> #{created_event.date} </span></p>"
      end
    end
    output.html_safe
  end
end

app/views/events/_form.html.erb
<div class='container'>
  <h1 class='title is-center'>Create Event</h1>
  <%= form_with model: @created_event, url: event_create_path do |f| %>
  <%= errors(@created_event) %>
  <div class="field">
    <p class="control has-icons-left has-icons-right">
    <%= f.text_field :title,  placeholder: 'Enter event title', class: 'input is-info' %>
      <span class="icon is-small is-left">
        <i class="fas fa-envelope"></i>
      </span>
      <span class="icon is-small is-right">
        <i class="fas fa-check"></i>
      </span>
    </p>
  </div>
  <div class="field">
    <p class="control has-icons-left has-icons-right">
    <%= f.text_area :description,  placeholder: 'Enter event description', class: 'input is-info', size: "70x5" %>
      <span class="icon is-small is-left">
        <i class="fas fa-pen"></i>
      </span>
      <span class="icon is-small is-right">
        <i class="fas fa-check"></i>
      </span>
    </p>
  </div>
  <div class="field">
    <p class="control has-icons-left has-icons-right">
    <%= f.date_field :date,  placeholder: 'Enter event date', class: 'input is-info' %>
      <span class="icon is-small is-left">
        <i class="fas fa-calendar-plus"></i>
      </span>
      <span class="icon is-small is-right">
        <i class="fas fa-check"></i>
      </span>
    </p>
  </div>
  <div class="field">
    <p class="control has-icons-left has-icons-right">
    <%= f.text_field :location,  placeholder: 'Enter event location', class: 'input is-info' %>
      <span class="icon is-small is-left">
        <i class="fas fa-map-marker-alt"></i>
      </span>
      <span class="icon is-small is-right">
        <i class="fas fa-check"></i>
      </span>
    </p>
  </div>
  
  <div class="field">
    <p class="control">
      <%= f.submit 'Create Event', class: 'button is-success' %> 
    </p>
  </div>
  <% end %>
</div>

app/views/events/_show_events.html.erb
<%= all_events %>
</div>
</section>

<section class='section container'>
  <div class='content'>
    <h4> Upcoming Events </h4>
    <ul>
      <%= return_upcoming_events(@created_events) %>
    </ul>
  </div>

  <div class='content'>
    <h4> Past Events </h4>
    <ul>
      <%= return_past_events(@created_events) %>  
    </ul>
  </div>

app/views/events/index.html.erb
<section class='section container'>
<div class='content'>
    <%= render 'show_events' %>
  </div>
</section>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<section class='section container'><div class='content'>
<p>Event Organiser: <strong><%= @created_event.creator.name.upcase!%></strong></p>
<p>Number of Attendees: <%= @created_event.attendees.count %></p>

</div>
</section>
<section class='section container'>
<article class="panel is-info is-two-third">
  <p class="panel-heading">
    Event
    <%= @created_event.title %>
  </p><br>   
      <%= show_status(current_user) %> 
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
    <p> <%= @created_event.description %> | <%= @created_event.date %>  | <%= @created_event.location %> </p>
  </a>
</article>

<article class="panel is-success is-one-third">
  <p class="panel-heading"> Attendees
  </p>
    <% @created_event.attendees.each do |attendee|%>
  <a class="panel-block is-active">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span><%= attendee.name %>
  </a>
    <% end %>
</article>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css' %>
    <%= stylesheet_link_tag 'https://use.fontawesome.com/releases/v5.7.0/css/all.css' %>
  </head>

  <body>
  <%= render partial: 'shared/flash' %>
  <nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "Private Events", root_path, class: "navbar-item" %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
        <%= link_to "Show Events", events_path, class: "navbar-item" %>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">

        <div class="buttons">
        <%= header_display %>
        </div>
      </div>
    </div>
  </div>
</nav>

    
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<br>
<%= flash_notice %>

app/views/users/_events.html.erb
<% if logged_in?  %>
  <% if Event.past_events.any? %>
    <p>You have the following <%= Event.past_events.count %> past events</p>
    <ul>
        <% Event.past_events.each do |event| %>
          <li><%= event.title %> | <%= event.date %> | <%= event.location %> </li>
        <% end %>  
    </ul>
  <% else %>
    <p> You have no past events. </p> 
  <% end %>

  <% if Event.upcoming_events.any? %>
    <p>You have the following <%= Event.upcoming_events.count %> upcoming events</p>
    <ul>
        <% Event.upcoming_events.each do |event| %>
          <li><%= event.title %> | <%= event.date %> | <%= event.location %> </li>
        <% end %>  
    </ul>
  <% else %>
    <p> You have no upcoming events. </p> 
  <% end %>
<% else %> 
   <% Event.all.each do |created_event| %>
        <h3 class='subtitle'> <%= created_event.title %> </h3>
        <p> <%= created_event.description %> <span> <%= created_event.date %> </span></p>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<div class='container'>
  <h1 class='title is-center'>Sign Up</h1>
  <%= form_with model: @user, url: sign_up_path do |f| %>
  <%= errors(@user) %>
  <div class="field">
    <p class="control has-icons-left has-icons-right">
    <%= f.text_field :name,  placeholder: 'Enter your name', class: 'input is-info' %>
      <span class="icon is-small is-left">
        <i class="fas fa-envelope"></i>
      </span>
      <span class="icon is-small is-right">
        <i class="fas fa-check"></i>
      </span>
    </p>
  </div>
  
  <div class="field">
    <p class="control">
      <%= f.submit 'Sign Up', class: 'button is-success' %> 
    </p>
  </div>
  <% end %>
</div>

app/views/users/_show.html.erb
<%= logged(Event) %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<section class='section container'>
<div class='content'>
  <%= show_user_create(current_user) %>
  
</div>
</section>

<section class='section container'>
<div class='content'>
<%= render 'show' %>
</div>
</section>

app/views/users/sign_in.html.erb
<div class='container'>
  <h1 class='title is-center'>Users#new</h1>
  <%= form_with model: @user do |f| %>
  <div class="field">
    <p class="control has-icons-left">
        <%= f.text_field :username,  placeholder: 'Enter your username', class: 'input is-info' %>
      <span class="icon is-small is-left">
        <i class="fas fa-lock"></i>
      </span>
    </p>
  </div>
  <div class="field">
    <p class="control">
      <%= f.submit 'Sign In', class: 'button is-success' %> 
    </p>
  </div>
  <% end %>
</div>